### ISSUE TITLE
does not display the input box in Arch Linux

### ISSUE THREAD

**Issue by mihado** [xgenvn/InputHelper#2]
hi. I'm using Sublime Text 2.0.1 build 2217
Arch Linux with Gnome 3.6
ibus works fine in other GTK and QT app however it doesn't work with Sublime.
I installed this Helper by using Package Control n' Manual method and they install fine.

However when I press ctrl + shift + z the input box does not appear.
I tried to type in InputHelper, enter in the selector (ctrl + shift + p) and it also does not appears.

**Comment by xgenvn** [comment]
Hi,
I guess the possible problem here is you haven't had pygtk2 and gtk module for python installed on your box yet.
Please use below commands then post the result back here, I'll fix if I can.

``` bash
cd ~/.config/sublime-text-2/Packages/InputHelper/lib/
python linux_text_input_gui.py
```

**Comment by mihado** [comment]
hi, thanks for the suggestion. 
I have python2 and 3 installed by default, and it seems like pygtk requires python2.
I just changed the call from python to python2 and the InputHelper works

**Comment by xgenvn** [comment]
I'm glad that you can solve the problem.
If you have any other issues, we can make new issues and discuss there. I'll mark this as closed.
