### ISSUE TITLE
centOS KDE4环境不能用

### ISSUE THREAD

**Issue by zhangyijun** [xgenvn/InputHelper#5]
输入完成后关闭窗口
Esc能正常退出

**Comment by xgenvn** [comment]
如果可以的话，你尝试下列命令：
cd ~/.config/sublime-text-2/Packages/InputHelper/lib/
python linux_text_input_gui.py

然后拷贝运行结果后到这边来，我及时检查一下。现在我没有KDE环境测试。
谢谢。
