### ISSUE TITLE
能不能做一个针对sublime 3.0的

### ISSUE THREAD

**Issue by lvshuang** [xgenvn/InputHelper#9]
刚刚发现原来的插件也是可以用的 呵呵

**Comment by xgenvn** [comment]
我已经测试过st3.0，你那边出现什么问题的？

**Comment by lvshuang** [comment]
没什么问题，用得挺好，只是直接clone到package里面不能用

2014-01-08 xgenvn notifications@github.com

**Comment by xgenvn** [comment]
已经更新ST3支持，直接用package installer安装吧。
